# Longform QA 数据集配置
evaluation_config:
  evaluation_datasets:
    - path: data/WaterBench/2-1_longform_qa.jsonl
      user_prompt: "You are a helpful assistant, please answer the following question within 300 words:\n{context}\n{input}"
      chat: true
      max_length: 150
      min_length: 1
